sudo: false
dist: trusty
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
jdk:
  - oraclejdk7
cache:
  ccache: true
  apt: true
  directories:
     - /usr/local/Cellar
     - ${HOME}/javadeps

addons:
   apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
      packages:
        - clang-4.0
        - g++-6
        - zlib1g-dev
        - libbz2-dev
        - libsnappy-dev
        - liblz4-dev
        - curl
        - libgflags-dev
        - libjemalloc-dev
        - libnuma-dev
env:
  - TEST_GROUP=platform_dependent1
  - TEST_GROUP=platform_dependent2
  - TEST_GROUP=platform_dependent3
  - TEST_GROUP=1
  - TEST_GROUP=2
  # Run java tests
  - JOB_NAME=java_test
  # Build ROCKSDB_LITE
  - JOB_NAME=lite_build
  # Build examples
  - JOB_NAME=examples

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - os: osx
    env: TEST_GROUP=1
  - os: osx
    env: TEST_GROUP=2

before_script:
  - if [[ "${CXX}" == 'clang++' ]]; then
      if [[ "${TRAVIS_OS_NAME}" == 'linux' ]]; then CXX=clang++-4.0; fi;
      export EXTRA_CXXFLAGS="-Wno-unused-command-line-argument";
      export EXTRA_CCFLAGS="-Wno-unused-command-line-argument";
    fi
  # test one linux g++ build with g++-6
  - if [[ "${TRAVIS_OS_NAME}" == 'linux' && "${CXX}" == 'g++' && "${JOB_NAME}" == 'unittests' ]]; then CXX=g++-6; fi
  - if [[ "${TRAVIS_OS_NAME}" == 'osx' ]]; then
      brew update;
      brew install ccache jemalloc snappy lz4 lzo xz zstd;
      brew link ccache;
    fi
  - mkdir -p "${HOME}"/bin ;
  - ln -s `which ccache` "${HOME}/bin/${CXX}"
  - export PATH="${HOME}/bin:${PATH}"
  - mkdir "${HOME}"/javadep
  - ln -s "${HOME}"/javadep java/test-libs
  # Limit the maximum number of open file descriptors to 8192
  - ulimit -n 8192 || true

script:
  - ${CXX} --version
  - if [[ "${TEST_GROUP}" == 'platform_dependent1' ]]; then OPT=-DTRAVIS V=1 ROCKSDBTESTS_END=external_sst_file_basic_test make -j4 check_some; fi
  - if [[ "${TEST_GROUP}" == 'platform_dependent2' ]]; then OPT=-DTRAVIS V=1 ROCKSDBTESTS_START=external_sst_file_basic_test ROCKSDBTESTS_END=checkpoint_test make -j4 check_some; fi
  - if [[ "${TEST_GROUP}" == 'platform_dependent3' ]]; then OPT=-DTRAVIS V=1 ROCKSDBTESTS_START=checkpoint_test ROCKSDBTESTS_END=db_block_cache_test make -j4 check_some; fi
  - if [[ "${TEST_GROUP}" == '1' ]]; then OPT=-DTRAVIS V=1 ROCKSDBTESTS_START=db_block_cache_test ROCKSDBTESTS_END=comparator_db_test make -j4 check_some; fi
  - if [[ "${TEST_GROUP}" == '2' ]]; then OPT=-DTRAVIS V=1 ROCKSDBTESTS_START=comparator_db_test make -j4 check_some; fi
  - if [[ "${JOB_NAME}" == 'java_test' ]]; then OPT=-DTRAVIS V=1 make clean jclean rocksdbjava jtest; fi
  - if [[ "${JOB_NAME}" == 'lite_build' ]]; then OPT="-DTRAVIS -DROCKSDB_LITE" V=1 make -j4 static_lib; fi
  - if [[ "${JOB_NAME}" == 'examples' ]]; then OPT=-DTRAVIS V=1 make -j4 static_lib; cd examples; make -j4; fi
  - ccache --show-stats

notifications:
    email:
      - leveldb@fb.com
    webhooks:
      - https://buildtimetrend.herokuapp.com/travis
