sudo: false
dist: trusty
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
jdk:
  - oraclejdk7
cache:
  - ccache
  - apt

addons:
   apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty', 'llvm-toolchain-trusty-3.9', 'llvm-toolchain-trusty-4.0']
      packages: ['clang-3.6', 'clang-3.9','clang-4.0', 'g++-5', 'g++-6', 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'libgflags-dev']
env:
  # Run all tests before db_block_cache_test (db_test, db_test2)
  - JOB_NAME=unittests ROCKSDBTESTS_END=db_block_cache_test
  # Run all tests starting from db_block_cache_test but can't do them all due to travis space constraints
  - JOB_NAME=unittests ROCKSDBTESTS_START=db_block_cache_test ROCKSDBTESTS_END=redis_test
  - JOB_NAME=unittests ROCKSDBTESTS_START=redis_test
  # Run java tests
  - JOB_NAME=java_test
  # Build ROCKSDB_LITE
  - JOB_NAME=lite_build
  - JOB_NAME=lite_build COMPILER=clang++-3.9
  - JOB_NAME=lite_build COMPILER=clang++-4.0

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - os: osx
    compiler: clang
    env: COMPILER=clang++-3.9
  - os: osx
    compiler: clang
    env: COMPILER=clang++-4.0
  - os: linux
    compiler: gcc
    env: COMPILER=clang++-4.0

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == 'linux' && "${CXX}" == 'clang++' ]]; then CXX=${COMPILER:+clang++-3.6}; fi
  # test linux g++ unittests build with g++-6
  - if [[ "${TRAVIS_OS_NAME}" == 'linux' && "${CXX}" == 'g++' && ( "${JOB_NAME}" == 'unittests' && "${ROCKSDBTESTS_END}" == db_block_cache_test || "${COMPILER}" == clang++-3.9 ) ]]; then CXX=g++-6; else CXX=g++-5; fi
  # Limit the maximum number of open file descriptors to 8192
  - ulimit -n 8192 || true

script:
  - ${CXX} --version
  - ( while [ 1 ]; do df -h; sleep 5; done ) &
  - DFPID=$!
  - if [[ "${JOB_NAME}" == 'unittests' ]]; then OPT=-DTRAVIS V=1 make -j4 check_some; fi
  - if [[ "${JOB_NAME}" == 'java_test' ]]; then OPT=-DTRAVIS V=1 make clean jclean rocksdbjava jtest; fi
  - if [[ "${JOB_NAME}" == 'lite_build' ]]; then OPT="-DTRAVIS -DROCKSDB_LITE" V=1 make -j4 static_lib; fi
  - kill $DFPID
notifications:
    email:
      - leveldb@fb.com
    webhooks:
      - https://buildtimetrend.herokuapp.com/travis
